name: olist_dbt
version: 1.0.0
config-version: 2
profile: olist_spark

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  olist_dbt:
    bronze:
      +schema: bronze
      +materialized: table
      +tags: ["bronze"]
      +file_format: parquet
    silver:
      +schema: silver
      +materialized: table
      +tags: ["silver"]
      +file_format: parquet
    gold:
      +schema: gold
      +materialized: table
      +tags: ["gold"]
      +file_format: parquet
