CREATE DATABASE IF NOT EXISTS olist;
USE olist;
DROP TABLE IF EXISTS customers;
CREATE TABLE customers USING PARQUET LOCATION 'hdfs://namenode:9000/olist/customers';
DROP TABLE IF EXISTS geolocation;
CREATE TABLE geolocation USING PARQUET LOCATION 'hdfs://namenode:9000/olist/geolocation';
DROP TABLE IF EXISTS order_items;
CREATE TABLE order_items USING PARQUET LOCATION 'hdfs://namenode:9000/olist/order_items';
DROP TABLE IF EXISTS order_payments;
CREATE TABLE order_payments USING PARQUET LOCATION 'hdfs://namenode:9000/olist/order_payments';
DROP TABLE IF EXISTS order_reviews;
CREATE TABLE order_reviews USING PARQUET LOCATION 'hdfs://namenode:9000/olist/order_reviews';
DROP TABLE IF EXISTS orders;
CREATE TABLE orders USING PARQUET LOCATION 'hdfs://namenode:9000/olist/orders';
DROP TABLE IF EXISTS products;
CREATE TABLE products USING PARQUET LOCATION 'hdfs://namenode:9000/olist/products';
DROP TABLE IF EXISTS sellers;
CREATE TABLE sellers USING PARQUET LOCATION 'hdfs://namenode:9000/olist/sellers';
DROP TABLE IF EXISTS category_translation;
CREATE TABLE category_translation USING PARQUET LOCATION 'hdfs://namenode:9000/olist/category_translation';
CREATE DATABASE IF NOT EXISTS olist_star;
USE olist_star;
DROP TABLE IF EXISTS dim_customer;
CREATE TABLE dim_customer USING PARQUET LOCATION 'hdfs://namenode:9000/olist/star/dim_customer';
DROP TABLE IF EXISTS dim_seller;
CREATE TABLE dim_seller USING PARQUET LOCATION 'hdfs://namenode:9000/olist/star/dim_seller';
DROP TABLE IF EXISTS dim_product;
CREATE TABLE dim_product USING PARQUET LOCATION 'hdfs://namenode:9000/olist/star/dim_product';
DROP TABLE IF EXISTS dim_date;
CREATE TABLE dim_date USING PARQUET LOCATION 'hdfs://namenode:9000/olist/star/dim_date';
DROP TABLE IF EXISTS dim_geolocation;
CREATE TABLE dim_geolocation USING PARQUET LOCATION 'hdfs://namenode:9000/olist/star/dim_geolocation';
DROP TABLE IF EXISTS fact_orders;
CREATE TABLE fact_orders USING PARQUET LOCATION 'hdfs://namenode:9000/olist/star/fact_orders';
DROP TABLE IF EXISTS fact_sales;
CREATE TABLE fact_sales USING PARQUET LOCATION 'hdfs://namenode:9000/olist/star/fact_sales';
DROP TABLE IF EXISTS fact_payments;
CREATE TABLE fact_payments USING PARQUET LOCATION 'hdfs://namenode:9000/olist/star/fact_payments';
DROP TABLE IF EXISTS fact_reviews;
CREATE TABLE fact_reviews USING PARQUET LOCATION 'hdfs://namenode:9000/olist/star/fact_reviews';
SHOW TABLES IN olist;
SHOW TABLES IN olist_star;